"""initial schema

The four tables as app.models.weather defined them up to commit af5bd72 (before ix_locations_lat_lon).
A database that the app already created with create_all() is at this revision: run
`alembic stamp 0001_initial_schema` once, then `alembic upgrade head`.

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-10-06 05:34:12.849948+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_weather_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temp_celsius', sa.Float(), nullable=True),
    sa.Column('temp_fahrenheit', sa.Float(), nullable=True),
    sa.Column('feels_like_celsius', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('weather_main', sa.String(length=100), nullable=True),
    sa.Column('weather_description', sa.String(length=300), nullable=True),
    sa.Column('weather_icon', sa.String(length=50), nullable=True),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True, comment='Raw API JSON for reference'),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('current_weather_cache', schema=None) as batch_op:
        batch_op.create_index('ix_cache_lat_lon', ['latitude', 'longitude'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_input', sa.String(length=500), nullable=False, comment='Original user-provided location string'),
    sa.Column('resolved_name', sa.String(length=500), nullable=False, comment='Human-readable resolved location name'),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('place_id', sa.String(length=500), nullable=True, comment='Google Places ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('weather_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False, comment='Start of requested date range'),
    sa.Column('date_to', sa.Date(), nullable=False, comment='End of requested date range'),
    sa.Column('label', sa.String(length=300), nullable=True, comment='Optional user-defined label for this query'),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='querystatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_queries_id'), ['id'], unique=False)

    op.create_table('weather_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_avg', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True, comment='Percentage 0-100'),
    sa.Column('pressure', sa.Float(), nullable=True, comment='hPa'),
    sa.Column('wind_speed', sa.Float(), nullable=True, comment='m/s'),
    sa.Column('wind_direction', sa.Integer(), nullable=True, comment='Degrees 0-360'),
    sa.Column('visibility', sa.Integer(), nullable=True, comment='Meters'),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True, comment='Percentage 0-100'),
    sa.Column('precipitation', sa.Float(), nullable=True, comment='mm'),
    sa.Column('snow', sa.Float(), nullable=True, comment='mm'),
    sa.Column('weather_main', sa.String(length=100), nullable=True, comment='e.g. Rain, Clear'),
    sa.Column('weather_description', sa.String(length=300), nullable=True),
    sa.Column('weather_icon', sa.String(length=50), nullable=True),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['weather_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_records_record_date'), ['record_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_records_record_date'))
        batch_op.drop_index(batch_op.f('ix_weather_records_id'))

    op.drop_table('weather_records')
    with op.batch_alter_table('weather_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_queries_id'))

    op.drop_table('weather_queries')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    with op.batch_alter_table('current_weather_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_cache_lat_lon')

    op.drop_table('current_weather_cache')
    # ### end Alembic commands ###
    # PostgreSQL keeps the enum type after its table is dropped.
    sa.Enum(name='querystatus').drop(op.get_bind(), checkfirst=True)
